[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/644ce45147a741f408fdc4c1"
  to = "https://abdullahsheriff.netlify.app/644ce45147a741f408fdc4c1"
  status = 200
